# Generated by Django 4.2.16 on 2024-10-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
