# Generated by Django 4.2.16 on 2024-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images/'),
        ),
    ]
